### ISSUE TITLE
Can specify custom template 500.html

### ISSUE THREAD

**Issue by juanpex** [ionelmc/django-monkey-team#1]
Would be nice to establish a proper template where context handle variables
  '<pre>% (data) s </ pre>'
'<script>% (extra) s </ script>'

Or directly use the default 500.html.

**Comment by ionelmc** [comment]
Yes this is on my todo list :)

**Comment by ionelmc** [comment]
Fixed in eca26958c57c4c0c68b7043898c6dccf6efaf1ec
