### ISSUE TITLE
Userscript not working in chrome

### ISSUE THREAD

**Issue by ckcollab** [ionelmc/django-monkey-team#3]
Hey there!  Thanks for this app, I can't wait to use it!

Right now it doesn't seem the userscript is working at all... I'm in Chrome.  It takes me to the appropriate page and I can decode it, but not automatically view it.

Thanks for any help!

**Comment by ionelmc** [comment]
Are you getting any errors in the developer console ?

**Comment by xyb** [comment]
/admin/monkey_team/setup/monkey-team.user.js's content be escaped, so it cause a javascript error that not shows up when using Chrome, but with Opera:

```
Syntax error at line 18: expected expression, got '&'
s;var c=new a;e&amp;&amp;c.mixIn(e);c.$s
--------------------^
```

After I replace downloaded js's "var CryptoJS" block with the src/monkey_team/aes.js, problem resolved.

**Comment by ionelmc** [comment]
Thanks, this must have been the problem.
